{
   "node": true,
   "esnext": true,
   "bitwise": true,
   "camelcase": true,
   "curly": true,
   "eqeqeq": true,
   "forin": true,
   "immed": true,
   "indent": 4,
   "latedef": true,
   "newcap": true,
   "noarg": true,
   "quotmark": "double",
   "regexp": true,
   "undef": true,
   "strict": true,
   "trailing": true,
   "smarttabs": true
}