#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

function failCommit() {
    tput setaf 1
    echo "----------------------------------------"
    echo "FATAL ERROR: $1"
    echo "----------------------------------------"
    tput sgr0
    exit 1
}

function testFail() {
    tput setaf 3
    echo "----------------------------------------"
    echo "$1"
    echo "----------------------------------------"
    tput sgr0
}

echo 'Running JSHint...'

REPO=$(pwd)
JSHINT=${REPO}/node_modules/.bin/jshint

FILES=$(find . -name '*.js' ! -path "./node_modules/*" ! -path "./build/*" ! -path "./lib/plugins*" ! -path "./scripts*")
RESULT=$(${JSHINT} ${FILES} --config=${REPO}/.jshintrc)

if egrep "errors" <<< "$RESULT"; then
    num=$(grep "[0-9]+ error" <<< "$RESULT")
    testFail "JSHint: $num"
    echo "$RESULT"
    echo ''
    hintFailed=1
fi

if [[ $hintFailed -gt 0 ]]; then
    failCommit "Hint Errors"
fi
